name: Hugo build and deploy
on:
    push:

env:
    TZ: Asia/Shanghai # 设置当前环境时区

jobs:
    Actions-Hugo-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
              with:
                  submodules: recursive # Fetch Hugo themes (true OR recursive)
                  fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

            - name: Git Configuration
              run: |
                  git config --global core.quotePath false
                  git config --global core.autocrlf false
                  git config --global core.safecrlf true
                  git config --global core.ignorecase false
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: 0.122.0
                  extended: true
            - name: Build Hugo static files
              run: hugo -v --gc --minify
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # secret 中设置好私钥
                  external_repository: nyancccat/nyancccat.github.io # Page 仓库
                  publish_branch: master # Page 仓库的分支
                  publish_dir: ./public # 静态网页路径
                  commit_message: ${{ github.event.head_commit.message }}
